name: "Hem & Hadley's"
favicon: null
layout_spectrum: 0.25645
typography_spectrum: 0.30781
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#527fa5'
    - '#1b1919'
    - '#454444'
    - '#aeaeae'
  brandStrength: 1
  lightness: 0.625
  saturation: 0
  rhythmicContrast: 0
purpose:
  - name: awareness
    item: null
    url: null
